---
title: "Adapting the DynLib database layout for Spectra"
format:
  html:
    toc: true
    self-contained: true
author: "Ahlam Mentag, Johannes Rainer"
---

## Shiny Documents

In this document we combined all Dynlib sub databases to one global SQLite database.

```{r}
library(DBI)
library(RSQLite)

# Define paths to source databases
source_dbs <- c("C:/Users/amentag/Desktop/these/These/clones/RDynlib/data/DyLib_FTMS_neg2.sqlite", 
                "C:/Users/amentag/Desktop/these/These/clones/RDynlib/data/DyLib_FTMS_pos2.sqlite", 
                "C:/Users/amentag/Desktop/these/These/clones/RDynlib/data/DyLib_QTOF_neg2.sqlite", 
                "C:/Users/amentag/Desktop/these/These/clones/RDynlib/data/DyLib_QTOF_pos.sqlite")

# Define path for the merged output database
merged_db_path <- "C:/Users/amentag/Desktop/these/These/clones/RDynlib/data/DyLib_combined3.sqlite"

```

```{r}
# Create a new merged database 
merged_con <- dbConnect(SQLite(), merged_db_path)

# Loop through each source database
for (db_path in source_dbs) {
  # Connect to the source database
  con <- dbConnect(SQLite(), db_path)
  
  # Get table names
  tables <- dbListTables(con)
  
  for (table in tables) {
    # Read data from source table
    data <- dbReadTable(con, table)
    
    # Append or create the table in the merged DB
    if (dbExistsTable(merged_con, table)) {
      dbWriteTable(merged_con, table, data, append = TRUE)
    } else {
      dbWriteTable(merged_con, table, data)
    }
  }
  
  dbDisconnect(con)
}

```


```{r}
library(DBI)
library(RSQLite)

#Path to the combined database
merged_db_path <- "C:/Users/amentag/Desktop/these/These/clones/RDynlib/data/DyLib_combined3.sqlite"

# Connexion
con <- dbConnect(SQLite(), merged_db_path)

# Get table names
tables <- dbListTables(con)
print(tables)

```

```{r}
dbReadTable(con, "experiment")
```

```{r}
dbReadTable(con, "metadata")
```

```{r}
dbReadTable(con, "ms_compound")
```

```{r}
dbReadTable(con, "msms_spectrum")

```


```{r}
df <- dbGetQuery(con, "SELECT * FROM msms_spectrum WHERE dataOrigin = 'FTMS_pos' ")
df
```


```{r}
dbReadTable(con, "msms_spectrum_peak")
```



Here we remove unused columns from experiment table
```{r}

experiment_df <- dbGetQuery(con, "SELECT * FROM experiment")

#here we remove "x", "x.1" columns from experiment table 
experiment_df <- experiment_df[, !names(experiment_df) %in% c("x", "x.1")]
dbExecute(con, "DROP TABLE experiment")
dbWriteTable(con, "experiment", experiment_df)

#the columns have been successfully deleted
dbGetQuery(con, "PRAGMA table_info(experiment)")

```

Next we create a compDB object from the combined database, from which we create 
a spectra object
```{r}
library(CompoundDb)

#we convert the sql database to a Compdb object
cdb <- CompDb(dbf)
#we convert the Compdb object to a spectra object
sp <- Spectra(cdb)

spectraData(sp)
```

