cspp.display<-function(dbkey,base.dir,finlist,SubDB,
					nr_col=NULL,comp_add=NULL){
	if (is.null(nr_col)) nr_col<-35
	TMP<-SelectSubDB(base.dir,finlist,SubDB)
	subDB<-TMP[[1]]
	if (is.null(comp_add)) {
	 setwd(TMP[[4]])
	 comp_add<-read.table("compound_add.txt",header=T,sep="\t",
					stringsAsFactors=FALSE)
	}
	cspp.res<-data.frame(conv.type=character(),compid.prod=integer(),
			ions.prod=as.integer(),ave.common=as.numeric(),
			ave.dot=as.numeric(),prod.name=as.character(),
			stringsAsFactors=FALSE)
	i=3
	j=1
	repeat{
	 compid.prod<-as.integer(strsplit(comp_add[dbkey,i],"!!")[[1]][3])
	 if(is.na(compid.prod)){
	  if(i==nr_col)break
	  i=i+1
	  next
	 }else{
	  cspp.res[j,1]<-colnames(comp_add)[i]
	  cspp.res[j,2]<-compid.prod
	  cspp.res[j,3]<-as.integer((strsplit(strsplit(comp_add[dbkey,i],"!!")[[1]][2],"!")[[1]][1]))
	  cspp.res[j,4]<-as.numeric((strsplit(strsplit(comp_add[dbkey,i],"!!")[[1]][2],"!")[[1]][2]))
	  cspp.res[j,5]<-as.numeric((strsplit(strsplit(comp_add[dbkey,i],"!!")[[1]][2],"!")[[1]][3]))
	  compid.prod_row<-which(as.integer(subDB[[1]][,3])%in%as.integer(compid.prod))
	  cspp.res[j,6]<-as.character(subDB[[1]][compid.prod_row,5])
	 }
	 if(i==nr_col)break
	 i=i+1
	 j=j+1
	}
	return(cspp.res)
}
