gnps.display<-function(dbkey,base.dir,finlist,SubDB,
				nr_col2=NULL,gnps_add=NULL){
	if (is.null(nr_col2)) nr_col2<-6
	TMP<-SelectSubDB(base.dir,finlist,SubDB)
	subDB<-TMP[[1]]
	if (is.null(gnps_add)) {
	 setwd(TMP[[4]])
	 gnps_add<-read.table("gnps_add.txt",header=T,sep="\t",
					stringsAsFactors=FALSE)
	}
	gnps.res<-data.frame(massdiff=numeric(),compid.prod=integer(),
			ions.prod=as.integer(),ave.common=as.numeric(),
			ave.dot=as.numeric(),prod.name=as.character(),
			stringsAsFactors=FALSE)
	i=2
	j=1
	repeat{
	 compid.prod<-as.integer(strsplit(strsplit(gnps_add[dbkey,i],"!!")[[1]][2],"!")[[1]][4])
	 if(is.na(compid.prod)){
	  if(i==nr_col2)break
	  i=i+1
	  next
	 }else{
	  gnps.res[j,1]<-as.numeric(strsplit(gnps_add[dbkey,i],"!!")[[1]][3])
	  gnps.res[j,2]<-compid.prod
	  gnps.res[j,3]<-as.integer(strsplit(strsplit(gnps_add[dbkey,i],"!!")[[1]][2],"!")[[1]][1])
	  gnps.res[j,4]<-as.numeric((strsplit(strsplit(gnps_add[dbkey,i],"!!")[[1]][2],"!")[[1]][2]))
	  gnps.res[j,5]<-as.numeric((strsplit(strsplit(gnps_add[dbkey,i],"!!")[[1]][2],"!")[[1]][3]))
	  compid.prod_row<-which(as.integer(subDB[[1]][,3])%in%as.integer(compid.prod))
	  gnps.res[j,6]<-as.character(subDB[[1]][compid.prod_row,5])
	 }
	 if(i==nr_col2)break
	 i=i+1
	 j=j+1
	}
	return(gnps.res)
}