MSnplot<-function(dbkey,base.dir,finlist,SubDB,TMP=NULL,single=NULL,
				prcx=NULL,wh=NULL){
	if(is.null(TMP))TMP<-SelectSubDB(base.dir,finlist,SubDB)
	if(is.null(prcx))prcx=0.6
	subDB<-TMP[[1]]
	dbkey_row<-which(as.integer(subDB[[1]][,3])%in%as.integer(dbkey))
	if(subDB[[10]][[dbkey_row]]!="NULL"){
	 ms3id.int<-as.integer(unlist(strsplit(subDB[[10]][[dbkey_row]],split=",")))
	 msnle<-length(ms3id.int)+1
	}else{
	 msnle<-1
	}
	if(is.null(single)){
	 row.nr<-floor(sqrt(msnle))
	 col.nr<-ceiling(msnle/row.nr)
	 oldpar<-par(no.readonly=T)
	 par(mfrow=as.integer(c(row.nr,col.nr)))
	 single<-"single"
	}
	MS2specplot(dbkey,base.dir,finlist,SubDB,TMP=TMP,single=single,prcx=prcx)
	if(subDB[[10]][[dbkey_row]]!="NULL"){
	 ms3i=1
	 while(ms3i<=length(ms3id.int)){
	  MS3specplot(dbkey,base.dir,finlist,SubDB,TMP=TMP,single=single,
				prcx=prcx,wh=ms3i)
	  ms3i=ms3i+1
	 }
	}
}

# MSnplot(dbkey=2459,base.dir,finlist,SubDB="FTneg")