rank.GNPS<-function(gnps.df,gnps_add,Prod.dat,inp.x){
	scor<-gnps.df[,7]*gnps.df[,8]+gnps.df[,9]*gnps.df[,10]
	gnps.df<-data.frame(gnps.df,scor)
	gnps.df<-gnps.df[order(gnps.df[,15]),]
	ave.cnt<-(gnps.df[,12]+gnps.df[,14])/2
	ave.dot<-(gnps.df[,8]+gnps.df[,10])/2
	massdiff<-abs(inp.x[gnps.df[,4],5]-inp.x[gnps.df[,1],5])
	gnps.df<-data.frame(gnps.df,ave.cnt,ave.dot,massdiff)
	if(dim(gnps.df)[1]!=0){
	 k=1
	 while(k<=dim(gnps.df)[1]){
	  compid.sub<-gnps.df[k,1]
	  compid.prod<-gnps.df[k,4]
	  gnps.name<-paste("GNPS","!!",gnps.df[k,6],"!",
				gnps.df[k,16],"!",gnps.df[k,17],
				"!",compid.prod,"!!",round(gnps.df[k,18],3),sep="")
#	  print(gnps.name)
	  gnps_add[compid.sub,k+1]<-gnps.name
	  if(k==5)break
	  k=k+1
	 }
	}
	return(gnps_add) 
}
